//
//  DetailProductInteractor.swift
//  Lodjinha
//
//  Created by ely.assumpcao.ndiaye on 20/06/19.
//  Copyright (c) 2019 ely.assumpcao.ndiaye. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DetailProductBusinessLogic
{
    func doLoadInitialData(request: DetailProduct.Load.Request)
}

protocol DetailProductDataStore
{
    var productId: Int { get set }
}

class DetailProductInteractor: DetailProductBusinessLogic, DetailProductDataStore
{
    
    
    var presenter: DetailProductPresentationLogic?
    var worker: DetailProductWorker?
    var productId: Int = 0
    
    // MARK: Do something
    
    func doLoadInitialData(request: DetailProduct.Load.Request)
    {
        worker = DetailProductWorker()
        worker?.fetchProductById(productId: productId, completionHandler: { produto in
            let response = DetailProduct.Load.Response(produtos: produto)
            self.presenter?.presentInitialData(response: response)
        })
        
    }
}

