//
//  DetailProductPresenter.swift
//  Lodjinha
//
//  Created by ely.assumpcao.ndiaye on 20/06/19.
//  Copyright (c) 2019 ely.assumpcao.ndiaye. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DetailProductPresentationLogic
{
  func presentInitialData(response: DetailProduct.Load.Response)
}

class DetailProductPresenter: DetailProductPresentationLogic
{
  weak var viewController: DetailProductDisplayLogic?
  
  // MARK: Do something
  
  func presentInitialData(response: DetailProduct.Load.Response)
  {
    let viewModel = DetailProduct.Load.ViewModel(produtos: response.produtos)
    viewController?.displayInitialData(viewModel: viewModel)
  }
}
