//
//  HomeInteractor.swift
//  Lodjinha
//
//  Created by ely.assumpcao.ndiaye on 16/06/19.
//  Copyright (c) 2019 ely.assumpcao.ndiaye. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HomeBusinessLogic
{
    func doLoadInitialData(request: HomeScenes.Load.Request)
    func doLoadDetailProducts(request: HomeScenes.DetailProduct.Request)
    func doLoadProductsList(request: HomeScenes.ProductsList.Request)
}

protocol HomeDataStore
{
    var productId: Int { get set }
    var categoriaId: Int { get set }
}

class HomeInteractor: HomeBusinessLogic, HomeDataStore
{
    var presenter: HomePresentationLogic?
    var worker: HomeWorker?
    var productId: Int = 0
    var categoriaId: Int = 0
    
    // MARK: Do something
    
    func doLoadInitialData(request: HomeScenes.Load.Request) {
        worker = HomeWorker()
        worker?.fetchBanners(completionHandler: { (banners) in
            self.worker?.fetchCategory(completionHandler: { (categories) in
                self.worker?.fetchProductsMoreSales(completionHandler: { (produtosMaisVendidos) in
                    //Prepara uma resposta que vai ser enviada para o PRESENTER
                    //Response serve para mandar os posts
                    let response = HomeScenes.Load.Response(banners: banners, categories: categories, produtosMaisVendidos: produtosMaisVendidos)
                    self.presenter?.presentInitalDatas(response: response)
                })
                
            })
            
        })
        
    }
    
    func doLoadDetailProducts(request: HomeScenes.DetailProduct.Request) {
        let product = request.product
          productId = product[0].id
        print("ProductId:\(productId)")
        let response = HomeScenes.DetailProduct.Response()
        presenter?.presentDetailProduct(response: response)
    }
    
    func doLoadProductsList(request: HomeScenes.ProductsList.Request) {
        let categoria = request.categoria
        categoriaId = categoria[0].id
        print("categoriaId:\(categoriaId)")
        let response = HomeScenes.ProductsList.Response()
        presenter?.presentProductsList(response: response)
    }
    
}


