//
//  HomeRouter.swift
//  Lodjinha
//
//  Created by ely.assumpcao.ndiaye on 16/06/19.
//  Copyright (c) 2019 ely.assumpcao.ndiaye. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol HomeRoutingLogic
{
    func routeToDetailProduct()
    func routeToProductsList()
}

protocol HomeDataPassing
{
    var dataStore: HomeDataStore? { get }
}

class HomeRouter: NSObject, HomeRoutingLogic, HomeDataPassing
{
    weak var viewController: HomeViewController?
    var dataStore: HomeDataStore?
    
    // MARK: Routing
    
    func routeToDetailProduct() {
        let storyboard = UIStoryboard(name: "Main", bundle: nil)
        let destinationVC = storyboard.instantiateViewController(withIdentifier: "DetailProductViewController") as! DetailProductViewController
        var destinationDS = destinationVC.router!.dataStore!
        passDataToDetailProduct(source: dataStore!, destination: &destinationDS)
        navigateToDetailProduct(source: viewController!, destination: destinationVC)
    }
    
    func routeToProductsList() {
        let storyboard = UIStoryboard(name: "Main", bundle: nil)
        let destinationVC = storyboard.instantiateViewController(withIdentifier: "ProductsViewController") as! ProductsViewController
        var destinationDS = destinationVC.router!.dataStore!
        passDataToProductsList(source: dataStore!, destination: &destinationDS)
        navigateToProductsList(source: viewController!, destination: destinationVC)
    }
    //func routeToSomewhere(segue: UIStoryboardSegue?)
    //{
    //  if let segue = segue {
    //    let destinationVC = segue.destination as! SomewhereViewController
    //    var destinationDS = destinationVC.router!.dataStore!
    //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
    //  } else {
    //    let storyboard = UIStoryboard(name: "Main", bundle: nil)
    //    let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
    //    var destinationDS = destinationVC.router!.dataStore!
    //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
    //    navigateToSomewhere(source: viewController!, destination: destinationVC)
    //  }
    //}
    
    // MARK: Navigation
    
    func navigateToDetailProduct(source: HomeViewController, destination: DetailProductViewController){
      source.show(destination, sender: nil)
    }
    
    func navigateToProductsList(source: HomeViewController, destination: ProductsViewController){
        source.show(destination, sender: nil)
    }
    
    // MARK: Passing data
    
    func passDataToDetailProduct(source: HomeDataStore, destination: inout DetailProductDataStore){
      destination.productId = source.productId
    }
    
    func passDataToProductsList(source: HomeDataStore, destination: inout ProductsDataStore){
        destination.categoriaId = source.categoriaId
    }
}
