//
//  HomeModels.swift
//  Lodjinha
//
//  Created by ely.assumpcao.ndiaye on 16/06/19.
//  Copyright (c) 2019 ely.assumpcao.ndiaye. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum HomeScenes
{
  // MARK: Use cases
  
  enum Load
  {
    struct Request
    {
    }
    struct Response
    {
        let banners: [Banner]
        let categories: [Categoria]
        let produtosMaisVendidos: [ProdutosMaisVendidos]
    }
    struct ViewModel
    {
        let banners: [Banner]
        let categories: [Categoria]
        let produtosMaisVendidos: [ProdutosMaisVendidos]
    }
  }
}
