//
//  HomeInteractor.swift
//  Lodjinha
//
//  Created by ely.assumpcao.ndiaye on 16/06/19.
//  Copyright (c) 2019 ely.assumpcao.ndiaye. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HomeBusinessLogic
{
    func doLoadInitialData(request: HomeScenes.Load.Request)
}

protocol HomeDataStore
{
    //var name: String { get set }
}

class HomeInteractor: HomeBusinessLogic, HomeDataStore
{
    var presenter: HomePresentationLogic?
    var worker: HomeWorker?
    //var name: String = ""
    
    // MARK: Do something
    
    func doLoadInitialData(request: HomeScenes.Load.Request)
    {
        worker = HomeWorker()
        worker?.fetchBanners(completionHandler: { (banners) in
            self.worker?.fetchCategory(completionHandler: { (categories) in
                //Prepara uma resposta que vai ser enviada para o PRESENTER
                //Response serve para mandar os posts
                let response = HomeScenes.Load.Response(banners: banners, categories: categories)
                self.presenter?.presentInitalDatas(response: response)
            })            
            
        })
        
    }
    
}


