//
//  ProductsRouter.swift
//  Lodjinha
//
//  Created by ely.assumpcao.ndiaye on 21/06/19.
//  Copyright (c) 2019 ely.assumpcao.ndiaye. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol ProductsRoutingLogic
{
    func routeToDetailProduct()
    //func routeToSomewhere(segue: UIStoryboardSegue?)
    
}

protocol ProductsDataPassing
{
    var dataStore: ProductsDataStore? { get }
}

class ProductsRouter: NSObject, ProductsRoutingLogic, ProductsDataPassing
{
    weak var viewController: ProductsViewController?
    var dataStore: ProductsDataStore?
    
    // MARK: Routing
    
    func routeToDetailProduct() {
        //Main
        let storyboard = UIStoryboard(name: "Main", bundle: nil)
        let destinationVC = storyboard.instantiateViewController(withIdentifier: "DetailProductViewController") as! DetailProductViewController
        var destinationDS = destinationVC.router!.dataStore!
        passDataToDetailProduct(source: dataStore!, destination: &destinationDS)
        navigateToDetailProduct(source: viewController!, destination: destinationVC)
    }
    
    
    // MARK: Navigation
    
    func navigateToDetailProduct(source: ProductsViewController, destination: DetailProductViewController){
        source.show(destination, sender: nil)
    }
    
    // MARK: Passing data
    
    func passDataToDetailProduct(source: ProductsDataStore, destination: inout DetailProductDataStore){
        destination.productId = source.productId
    }
}
