//
//  ProductsPresenter.swift
//  Lodjinha
//
//  Created by ely.assumpcao.ndiaye on 21/06/19.
//  Copyright (c) 2019 ely.assumpcao.ndiaye. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ProductsPresentationLogic
{
    func presentInitialData(response: Products.Load.Response)
    func presentDetailProduct(response: Products.DetailProduct.Response)
}

class ProductsPresenter: ProductsPresentationLogic
{
    weak var viewController: ProductsDisplayLogic?
    
    // MARK: Do something
    
    func presentInitialData(response: Products.Load.Response) {
        let viewModel = Products.Load.ViewModel(produtos: response.produtos)
        viewController?.displayInitialData(viewModel: viewModel)
    }
    
    func presentDetailProduct(response: Products.DetailProduct.Response) {
        let viewModel = Products.DetailProduct.ViewModel()
        viewController?.displayDetailProduct(viewModel: viewModel)
    }
}
