//
//  ProductsModels.swift
//  Lodjinha
//
//  Created by ely.assumpcao.ndiaye on 21/06/19.
//  Copyright (c) 2019 ely.assumpcao.ndiaye. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Products
{
    // MARK: Use cases
    
    enum Load{
        struct Request
        {
        }
        struct Response
        {
            let produtos: [Produtos]
        }
        struct ViewModel
        {
            let produtos: [Produtos]
        }
    }
    
    enum DetailProduct {
        struct Request {
            let product : [DataProdutos]
        }
        struct Response {}
        struct ViewModel {}
    }
}
